import os, sys
import shutil
import datetime
import filecmp

strcmd = r'd:\py\backup\27012016-132510_full\testtesttsetsetsetsettesttesttsetsetsetsettesttesttsetsetsetsettesttesttsetsetsetsettesttesttsetsetsetsettesttesttsetsetsetsettesttesttsetsetsetsettesttesttsetsetsetsettesttesttsetsetsetsettesttesttsetsetsetsettesttesttsetsetsetsettesttesttsetset.txt'
print('STR_cmd -> ',len(strcmd))
print(strcmd)
strscript = 'testtesttsetsetsetsettesttesttsetsetsetsettesttesttsetsetsetsettesttesttsetsetsetsettesttesttsetsetsetsettesttesttsetsetsetsettesttesttsetsetsetsettesttesttsetsetsetsettesttesttsetsetsetsettesttesttsetsetsetsettesttesttsetsetsetsettesttesttsetset.txt'
print('STR_script -> ',len(strscript))

bstr = b'byte'
print(bstr.encode('utf-8'))
